apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubedb
  name: verticalautoscalers.autoscaling.kubedb.com
spec:
  group: autoscaling.kubedb.com
  names:
    categories:
    - datastore
    - kubedb
    - appscode
    kind: VerticalAutoscaler
    listKind: VerticalAutoscalerList
    plural: verticalautoscalers
    shortNames:
    - vascaler
    singular: verticalautoscaler
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              resourcePolicy:
                properties:
                  containerPolicies:
                    items:
                      properties:
                        containerName:
                          type: string
                        controlledResources:
                          items:
                            type: string
                          type: array
                        controlledValues:
                          type: string
                        maxAllowed:
                          additionalProperties:
                            anyOf:
                            - type: integer
                            - type: string
                            pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                            x-kubernetes-int-or-string: true
                          type: object
                        minAllowed:
                          additionalProperties:
                            anyOf:
                            - type: integer
                            - type: string
                            pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                            x-kubernetes-int-or-string: true
                          type: object
                        mode:
                          type: string
                      type: object
                    type: array
                type: object
              targetRef:
                properties:
                  apiGroup:
                    type: string
                  kind:
                    type: string
                  name:
                    type: string
                required:
                - kind
                - name
                type: object
              updatePolicy:
                properties:
                  updateMode:
                    type: string
                type: object
            required:
            - targetRef
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      format: date-time
                      type: string
                    message:
                      type: string
                    observedGeneration:
                      format: int64
                      type: integer
                    reason:
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              recommendation:
                properties:
                  containerRecommendations:
                    items:
                      properties:
                        containerName:
                          type: string
                        lowerBound:
                          additionalProperties:
                            anyOf:
                            - type: integer
                            - type: string
                            pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                            x-kubernetes-int-or-string: true
                          type: object
                        target:
                          additionalProperties:
                            anyOf:
                            - type: integer
                            - type: string
                            pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                            x-kubernetes-int-or-string: true
                          type: object
                        uncappedTarget:
                          additionalProperties:
                            anyOf:
                            - type: integer
                            - type: string
                            pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                            x-kubernetes-int-or-string: true
                          type: object
                        upperBound:
                          additionalProperties:
                            anyOf:
                            - type: integer
                            - type: string
                            pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                            x-kubernetes-int-or-string: true
                          type: object
                      required:
                      - target
                      type: object
                    type: array
                type: object
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubedb
  name: verticalautoscalercheckpoints.autoscaling.kubedb.com
spec:
  group: autoscaling.kubedb.com
  names:
    kind: VerticalAutoscalerCheckpoint
    listKind: VerticalAutoscalerCheckpointList
    plural: verticalautoscalercheckpoints
    singular: verticalautoscalercheckpoint
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              containerName:
                type: string
              vpaObjectName:
                type: string
            type: object
          status:
            properties:
              cpuHistogram:
                properties:
                  bucketWeights:
                    additionalProperties:
                      format: int32
                      type: integer
                    type: object
                  referenceTimestamp:
                    format: date-time
                    type: string
                  totalWeight:
                    format: float
                    type: number
                type: object
              firstSampleStart:
                format: date-time
                type: string
              lastSampleStart:
                format: date-time
                type: string
              lastUpdateTime:
                format: date-time
                type: string
              memoryHistogram:
                properties:
                  bucketWeights:
                    additionalProperties:
                      format: int32
                      type: integer
                    type: object
                  referenceTimestamp:
                    format: date-time
                    type: string
                  totalWeight:
                    format: float
                    type: number
                type: object
              totalSamplesCount:
                format: int64
                type: integer
              version:
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
